### ISSUE TITLE
Unable to generate HTML

### ISSUE THREAD

**Issue by dmitrym0** [appbaseio/docbase-manual#1]
Hello, the installation was successful however running `grunt` fails:

```
> grunt docbase

Running "docbase:def" (docbase) task
starting
Erro generating page: build_html/index.html
```

This is latest version installed via npm, on mac 10.10.5.

**Comment by siddharthlatest** [comment]
We're working on the issue - see [#15](https://github.com/appbaseio/Docbase/issues/15).

**Comment by dmitrym0** [comment]
Oops apologies for entering this in the wrong repo. Closing as duplicate.
